/*
 * FILE:
 *   sdl_offscreen_buffer.cpp
 *
 * AUTHOR:
 *   Stephen Thompson <stephen@solarflare.org.uk>
 *
 * COPYRIGHT:
 *   Copyright (C) Stephen Thompson, 2008 - 2026.
 *
 *   This file is part of the "Coercri" software library. Usage of "Coercri"
 *   is permitted under the terms of the Boost Software License, Version 1.0,
 *   the text of which is displayed below.
 *
 *   Boost Software License - Version 1.0 - August 17th, 2003
 *
 *   Permission is hereby granted, free of charge, to any person or organization
 *   obtaining a copy of the software and accompanying documentation covered by
 *   this license (the "Software") to use, reproduce, display, distribute,
 *   execute, and transmit the Software, and to prepare derivative works of the
 *   Software, and to permit third-parties to whom the Software is furnished to
 *   do so, all subject to the following:
 *
 *   The copyright notices in the Software and this entire statement, including
 *   the above license grant, this restriction and the following disclaimer,
 *   must be included in all copies of the Software, in whole or in part, and
 *   all derivative works of the Software, unless such copies or derivative
 *   works are solely in the form of machine-executable object code generated by
 *   a source language processor.
 *
 *   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *   FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 *   SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 *   FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 *   ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 *   DEALINGS IN THE SOFTWARE.
 *
 */

#include "sdl_offscreen_buffer.hpp"
#include "sdl_gfx_context.hpp"
#include "../../core/coercri_error.hpp"

#include <string>

namespace Coercri {

    SDLOffscreenBuffer::SDLOffscreenBuffer(SDLWindow *window_, SDL_Renderer *renderer_, int w, int h)
        : window(window_), renderer(renderer_), width(w), height(h), texture(nullptr)
    {
        SDL_RendererInfo info;
        Uint32 format = SDL_PIXELFORMAT_RGBA8888;
        if (SDL_GetRendererInfo(renderer, &info) == 0 && info.num_texture_formats > 0) {
            format = info.texture_formats[0];
        }

        texture = SDL_CreateTexture(renderer, format, SDL_TEXTUREACCESS_TARGET, w, h);
        if (!texture) {
            throw CoercriError(std::string("SDL_CreateTexture failed: ") + SDL_GetError());
        }
    }

    SDLOffscreenBuffer::~SDLOffscreenBuffer()
    {
        SDL_DestroyTexture(texture);
    }

    std::unique_ptr<GfxContext> SDLOffscreenBuffer::createGfxContext()
    {
        if (SDL_SetRenderTarget(renderer, texture) != 0) {
            throw CoercriError(std::string("SDL_SetRenderTarget failed: ") + SDL_GetError());
        }
        return std::unique_ptr<GfxContext>(new SDLGfxContext(window, renderer, /*is_offscreen=*/true));
    }

}
