/*
 * FILE:
 *   freetype_ttf_loader.cpp
 *
 * AUTHOR:
 *   Stephen Thompson <stephen@solarflare.org.uk>
 *
 * CREATED:
 *   21-May-2012
 *
 * COPYRIGHT:
 *   Copyright (C) Stephen Thompson, 2012 - 2025.
 *
 *   This file is part of the "Coercri" software library. Usage of "Coercri"
 *   is permitted under the terms of the Boost Software License, Version 1.0,
 *   the text of which is displayed below.
 *
 *   Boost Software License - Version 1.0 - August 17th, 2003
 *
 *   Permission is hereby granted, free of charge, to any person or organization
 *   obtaining a copy of the software and accompanying documentation covered by
 *   this license (the "Software") to use, reproduce, display, distribute,
 *   execute, and transmit the Software, and to prepare derivative works of the
 *   Software, and to permit third-parties to whom the Software is furnished to
 *   do so, all subject to the following:
 *
 *   The copyright notices in the Software and this entire statement, including
 *   the above license grant, this restriction and the following disclaimer,
 *   must be included in all copies of the Software, in whole or in part, and
 *   all derivative works of the Software, unless such copies or derivative
 *   works are solely in the form of machine-executable object code generated by
 *   a source language processor.
 *
 *   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *   FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 *   SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 *   FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 *   ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 *   DEALINGS IN THE SOFTWARE.
 *
 */

#include "freetype_ttf_loader.hpp"
#include "glyph_creator.hpp"
#include "lazy_bitmap_font.hpp"
#include "../core/coercri_error.hpp"

#include "boost/make_shared.hpp"

#include <ft2build.h>
#include FT_FREETYPE_H

#include <cstring>
#include <sstream>

namespace {
    // Error checking
    void FT_CHK_ERR(FT_Error err)
    {
        if (err) {
            std::ostringstream str;
            str << "Freetype error code " << err;
            throw Coercri::CoercriError(str.str());
        }
    }
}

namespace Coercri {
    class FTLibraryWrapper {
    public:
        FTLibraryWrapper()
        {
            FT_CHK_ERR(FT_Init_FreeType(&library));
        }

        ~FTLibraryWrapper()
        {
            FT_Done_FreeType(library);
        }

        FT_Library get() const { return library; }

    private:
        FT_Library library;
    };
}

namespace {

    // Conversion from Freetype 26.6 format
    inline int MyCeil(int x)
    {
        return (((x + 63) & -64) / 64);
    }

    // Freetype IO functions
    unsigned long ReadFunc(FT_Stream stream,
                           unsigned long offset,
                           unsigned char *buffer,
                           unsigned long count)
    {
        std::istream &str = *static_cast<std::istream*>(stream->descriptor.pointer);
        str.seekg(offset, std::ios_base::beg);

        // sometimes FT calls us w/ buffer == count == 0
        if (count == 0) return 0;

        str.read(reinterpret_cast<char*>(buffer), count);
        return str.gcount();
    }

    void CloseFunc(FT_Stream stream)
    {
        // We defer closing the stream until the FreetypeGlyphCreator
        // destructor runs.
    }


    // GlyphCreator implementation using FreeType
    class FreetypeGlyphCreator : public Coercri::GlyphCreator {
    public:
        FreetypeGlyphCreator(boost::shared_ptr<Coercri::FTLibraryWrapper> library, boost::shared_ptr<std::istream> str, int size);
        ~FreetypeGlyphCreator();

        Coercri::GlyphData createGlyph(char32_t codepoint) override;
        int getKern(char32_t left, char32_t right) override;
        int getLineHeight() const override { return line_height; }

    private:
        boost::shared_ptr<Coercri::FTLibraryWrapper> ft_library;  // Keep library alive
        boost::shared_ptr<std::istream> stream;    // Keep stream alive
        FT_StreamRec stream_rec;
        FT_Face face;
        int ascent;
        int line_height;
    };

    FreetypeGlyphCreator::FreetypeGlyphCreator(boost::shared_ptr<Coercri::FTLibraryWrapper> library,
                                               boost::shared_ptr<std::istream> str,
                                               int size)
        : ft_library(std::move(library)), stream(std::move(str)), face(nullptr)
    {
        // Calculate the file size, this is needed by Freetype
        stream->seekg(0, std::ios::end);
        size_t file_size = stream->tellg();
        stream->seekg(0, std::ios::beg);

        // Setup the Freetype "stream" object
        std::memset(&stream_rec, 0, sizeof(stream_rec));
        stream_rec.size = file_size;
        stream_rec.pos = 0;
        stream_rec.descriptor.pointer = stream.get();
        stream_rec.read = &ReadFunc;
        stream_rec.close = &CloseFunc;

        // Setup the FT_Open_Args
        FT_Open_Args args;
        std::memset(&args, 0, sizeof(args));
        args.flags = FT_OPEN_STREAM;
        args.stream = &stream_rec;

        // Open the font
        FT_CHK_ERR(FT_Open_Face(ft_library->get(), &args, 0, &face));

        try {
            // Set the size
            FT_CHK_ERR(FT_Set_Char_Size(face, 0, size * 64, 0, 0));

            // Get the font metrics
            ascent = MyCeil(face->size->metrics.ascender);
            const int descent = MyCeil(face->size->metrics.descender);
            const int ft_height = MyCeil(face->size->metrics.height);
            line_height = std::max(ascent - descent + 1, ft_height);

        } catch (...) {
            FT_Done_Face(face);
            throw;
        }
    }

    FreetypeGlyphCreator::~FreetypeGlyphCreator()
    {
        if (face) {
            FT_Done_Face(face);
        }
    }

    Coercri::GlyphData FreetypeGlyphCreator::createGlyph(char32_t codepoint)
    {
        Coercri::GlyphData result;

        // Convert codepoint to glyph index
        FT_UInt glyph_index = FT_Get_Char_Index(face, codepoint);

        // Load glyph image into the slot (erase previous one).
        // NOTE: we use FT_LOAD_FORCE_AUTOHINT, this is because
        // the results (in my opinion) look better with the
        // freetype autohinter, as compared to the native TrueType
        // hinting.
        FT_Error err = FT_Load_Glyph(face, glyph_index, FT_LOAD_RENDER | FT_LOAD_FORCE_AUTOHINT);
        if (err) {
            // Return empty glyph with zero advance on error
            return result;
        }

        result.width = face->glyph->bitmap.width;
        result.height = face->glyph->bitmap.rows;
        result.xofs = face->glyph->bitmap_left;
        result.yofs = ascent - face->glyph->bitmap_top;
        result.xadvance = face->glyph->advance.x >> 6;

        // Copy the bitmap data
        if (result.width > 0 && result.height > 0) {
            result.alpha.resize(result.width * result.height);
            const unsigned char *src = face->glyph->bitmap.buffer;
            for (int y = 0; y < result.height; ++y) {
                for (int x = 0; x < result.width; ++x) {
                    result.alpha[y * result.width + x] = src[x];
                }
                src += face->glyph->bitmap.pitch;
            }
        }

        return result;
    }

    int FreetypeGlyphCreator::getKern(char32_t left, char32_t right)
    {
        FT_UInt prev = FT_Get_Char_Index(face, left);
        FT_UInt next = FT_Get_Char_Index(face, right);

        if (prev && next) {
            FT_Vector delta;
            FT_Get_Kerning(face, prev, next, FT_KERNING_DEFAULT, &delta);
            return delta.x >> 6;
        }

        return 0;
    }
}


Coercri::FreetypeTTFLoader::FreetypeTTFLoader(boost::shared_ptr<Coercri::GfxDriver> driver)
    : gfx_driver(driver),
      ft_library(boost::make_shared<FTLibraryWrapper>())
{
}

boost::shared_ptr<Coercri::Font> Coercri::FreetypeTTFLoader::loadFont(boost::shared_ptr<std::istream> str,
                                                                      int size)
{
    auto glyph_creator = std::make_unique<FreetypeGlyphCreator>(ft_library, std::move(str), size);
    return boost::make_shared<LazyBitmapFont>(gfx_driver, std::move(glyph_creator));
}
