/*
 * FILE:
 *   glyph_creator.hpp
 *
 * PURPOSE:
 *   Interface for on-demand glyph creation, used by LazyBitmapFont.
 *
 * AUTHOR:
 *   Stephen Thompson <stephen@solarflare.org.uk>
 *
 * COPYRIGHT:
 *   Copyright (C) Stephen Thompson, 2008 - 2025.
 *
 *   This file is part of the "Coercri" software library. Usage of "Coercri"
 *   is permitted under the terms of the Boost Software License, Version 1.0,
 *   the text of which is displayed below.
 *
 *   Boost Software License - Version 1.0 - August 17th, 2003
 *
 *   Permission is hereby granted, free of charge, to any person or organization
 *   obtaining a copy of the software and accompanying documentation covered by
 *   this license (the "Software") to use, reproduce, display, distribute,
 *   execute, and transmit the Software, and to prepare derivative works of the
 *   Software, and to permit third-parties to whom the Software is furnished to
 *   do so, all subject to the following:
 *
 *   The copyright notices in the Software and this entire statement, including
 *   the above license grant, this restriction and the following disclaimer,
 *   must be included in all copies of the Software, in whole or in part, and
 *   all derivative works of the Software, unless such copies or derivative
 *   works are solely in the form of machine-executable object code generated by
 *   a source language processor.
 *
 *   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *   FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 *   SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 *   FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 *   ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 *   DEALINGS IN THE SOFTWARE.
 *
 */

#ifndef COERCRI_GLYPH_CREATOR_HPP
#define COERCRI_GLYPH_CREATOR_HPP

#include <cstdint>
#include <vector>

namespace Coercri {

    // Data for a single glyph, returned by GlyphCreator::createGlyph.
    struct GlyphData {
        // Alpha values for the glyph bitmap (row-major order).
        // Empty if the glyph has no visual representation (e.g. space).
        std::vector<unsigned char> alpha;

        // Dimensions of the alpha array.
        int width = 0;
        int height = 0;

        // Offset from the pen position to the top-left of the glyph bitmap.
        int xofs = 0;
        int yofs = 0;

        // How far to advance the pen position after drawing this glyph.
        int xadvance = 0;
    };

    // Interface for creating glyphs on demand.
    class GlyphCreator {
    public:
        virtual ~GlyphCreator() = default;

        // Create glyph data for the given Unicode codepoint.
        // Returns an empty GlyphData (with xadvance still set) if the glyph cannot be created.
        virtual GlyphData createGlyph(char32_t codepoint) = 0;

        // Get kerning adjustment between two codepoints.
        // Returns 0 if no kerning information is available.
        virtual int getKern(char32_t left, char32_t right) { return 0; }

        // Get the recommended line height for this font.
        virtual int getLineHeight() const = 0;
    };

}

#endif
