/*
 * FILE:
 *   graphic.hpp
 *
 * PURPOSE:
 *   "Device dependent" representation of a bitmap graphic
 *
 * AUTHOR:
 *   Stephen Thompson <stephen@solarflare.org.uk>
 *
 * COPYRIGHT:
 *   Copyright (C) Stephen Thompson, 2008 - 2025.
 *
 *   This file is part of the "Coercri" software library. Usage of "Coercri"
 *   is permitted under the terms of the Boost Software License, Version 1.0, 
 *   the text of which is displayed below.
 *
 *   Boost Software License - Version 1.0 - August 17th, 2003
 *
 *   Permission is hereby granted, free of charge, to any person or organization
 *   obtaining a copy of the software and accompanying documentation covered by
 *   this license (the "Software") to use, reproduce, display, distribute,
 *   execute, and transmit the Software, and to prepare derivative works of the
 *   Software, and to permit third-parties to whom the Software is furnished to
 *   do so, all subject to the following:
 *
 *   The copyright notices in the Software and this entire statement, including
 *   the above license grant, this restriction and the following disclaimer,
 *   must be included in all copies of the Software, in whole or in part, and
 *   all derivative works of the Software, unless such copies or derivative
 *   works are solely in the form of machine-executable object code generated by
 *   a source language processor.
 *
 *   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *   FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 *   SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 *   FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 *   ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 *   DEALINGS IN THE SOFTWARE.
 *
 */

#ifndef COERCRI_GRAPHIC_HPP
#define COERCRI_GRAPHIC_HPP

#include "boost/shared_ptr.hpp"

namespace Coercri {

    class PixelArray;

    // Flags for graphic creation
    enum class GraphicFlags : unsigned {
        None = 0,
        Dynamic = 1 << 0   // Texture can be modified after creation via setPixels()
    };

    inline GraphicFlags operator|(GraphicFlags a, GraphicFlags b)
    {
        return static_cast<GraphicFlags>(static_cast<unsigned>(a) | static_cast<unsigned>(b));
    }

    inline GraphicFlags operator&(GraphicFlags a, GraphicFlags b)
    {
        return static_cast<GraphicFlags>(static_cast<unsigned>(a) & static_cast<unsigned>(b));
    }

    inline bool hasFlag(GraphicFlags flags, GraphicFlags flag)
    {
        return (static_cast<unsigned>(flags) & static_cast<unsigned>(flag)) != 0;
    }

    class Graphic {
    public:
        virtual ~Graphic() { }

        virtual int getWidth() const = 0;
        virtual int getHeight() const = 0;
        virtual void getHandle(int &x, int &y) const = 0;
        virtual const PixelArray& getPixels() const = 0;

        // Update a region of the graphic's pixels (only valid for Dynamic graphics)
        virtual void setPixels(int x, int y, const PixelArray &pixels) = 0;
    };

}

#endif
