/*
 * FILE:
 *   key_code.hpp
 *
 * PURPOSE:
 *   Types and functions for working with keyboard keys.
 *
 * AUTHOR:
 *   Stephen Thompson <stephen@solarflare.org.uk>
 *
 * COPYRIGHT:
 *   Copyright (C) Stephen Thompson, 2008 - 2025.
 *
 *   This file is part of the "Coercri" software library. Usage of "Coercri"
 *   is permitted under the terms of the Boost Software License, Version 1.0, 
 *   the text of which is displayed below.
 *
 *   Boost Software License - Version 1.0 - August 17th, 2003
 *
 *   Permission is hereby granted, free of charge, to any person or organization
 *   obtaining a copy of the software and accompanying documentation covered by
 *   this license (the "Software") to use, reproduce, display, distribute,
 *   execute, and transmit the Software, and to prepare derivative works of the
 *   Software, and to permit third-parties to whom the Software is furnished to
 *   do so, all subject to the following:
 *
 *   The copyright notices in the Software and this entire statement, including
 *   the above license grant, this restriction and the following disclaimer,
 *   must be included in all copies of the Software, in whole or in part, and
 *   all derivative works of the Software, unless such copies or derivative
 *   works are solely in the form of machine-executable object code generated by
 *   a source language processor.
 *
 *   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *   FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 *   SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 *   FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 *   ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 *   DEALINGS IN THE SOFTWARE.
 *
 */

#ifndef COERCRI_KEY_CODE_HPP
#define COERCRI_KEY_CODE_HPP

#include <string>

namespace Coercri {

    // Class to represent a keyboard scancode (i.e., a key identified
    // by its position on the keyboard, rather than by the actual
    // character that it produces -- the former is keyboard layout
    // independent, the latter is not).

    // Since there are so many keys (in various keyboard standards),
    // we abandon the idea of trying to use numeric keycodes, and
    // instead represent keys as ASCII strings!

    // Note: Scancodes can be converted to user-readable names using
    // Window::getKeyName.

    // The symbolic names are supposed to be consistent across backends,
    // and stable over time. Here are some examples that most keyboards
    // will support:
    //   "a" to "z"
    //   "0" to "9"
    //   "return", "kp_enter" (numeric keypad enter)
    //   "tab", "backquote" (key above tab)
    //   "space"
    //   "backspace", "delete", "insert"
    //   "home", "end", "page_up", "page_down"
    //   "pause", "print_screen"
    //   "escape"
    //   "up", "down", "left", "right" (arrow keys)
    //   "f1" to "f12" (or more)
    //   "left_windows", "right_windows", "menu"
    //   "left_control", "left_shift", "right_control", "right_shift"
    // NB: Symbolic names never contain spaces.

    class Scancode {
    public:
        // Construct an invalid Scancode with empty symbolic name
        Scancode() { }

        // Construct a Scancode from a symbolic ASCII name like "w" or
        // "page_down"
        explicit Scancode(const std::string &sym_name)
            : sym_name(sym_name) { }

        // Get the symbolic ASCII name -- e.g. for saving to a file
        const std::string &getSymbolicName() const { return sym_name; }

        // Equality comparison
        bool operator==(const Scancode &other) const = default;

    private:
        std::string sym_name;
    };

    // Key Modifiers
    // (OR'd together)
    enum KeyModifier {
        KM_ALT = 1,
        KM_CONTROL = 2,
        KM_SHIFT = 4
    };
}

#endif
