/*
 * FILE:
 *   lazy_bitmap_font.hpp
 *
 * PURPOSE:
 *   Font class that loads glyphs on demand and stores them in a texture atlas.
 *
 * AUTHOR:
 *   Stephen Thompson <stephen@solarflare.org.uk>
 *
 * COPYRIGHT:
 *   Copyright (C) Stephen Thompson, 2008 - 2025.
 *
 *   This file is part of the "Coercri" software library. Usage of "Coercri"
 *   is permitted under the terms of the Boost Software License, Version 1.0,
 *   the text of which is displayed below.
 *
 *   Boost Software License - Version 1.0 - August 17th, 2003
 *
 *   Permission is hereby granted, free of charge, to any person or organization
 *   obtaining a copy of the software and accompanying documentation covered by
 *   this license (the "Software") to use, reproduce, display, distribute,
 *   execute, and transmit the Software, and to prepare derivative works of the
 *   Software, and to permit third-parties to whom the Software is furnished to
 *   do so, all subject to the following:
 *
 *   The copyright notices in the Software and this entire statement, including
 *   the above license grant, this restriction and the following disclaimer,
 *   must be included in all copies of the Software, in whole or in part, and
 *   all derivative works of the Software, unless such copies or derivative
 *   works are solely in the form of machine-executable object code generated by
 *   a source language processor.
 *
 *   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *   FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 *   SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 *   FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 *   ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 *   DEALINGS IN THE SOFTWARE.
 *
 */

#ifndef COERCRI_LAZY_BITMAP_FONT_HPP
#define COERCRI_LAZY_BITMAP_FONT_HPP

#include "font.hpp"
#include "rectangle.hpp"

#include "boost/noncopyable.hpp"
#include "boost/shared_ptr.hpp"

#include <cstdint>
#include <unordered_map>

namespace Coercri {

    class GfxDriver;
    class GlyphCreator;
    class Graphic;

    class LazyBitmapFont : public Font, boost::noncopyable {
    public:
        // Constructor.
        // glyph_creator: Used to create glyphs on demand. Ownership is taken.
        // atlas_width, atlas_height: Initial size of the texture atlas.
        LazyBitmapFont(boost::shared_ptr<GfxDriver> driver,
                       std::unique_ptr<GlyphCreator> glyph_creator,
                       int atlas_width = 256,
                       int atlas_height = 256);

        // Overridden from Font:
        void drawText(GfxContext &dest, int x, int y, const UTF8String &text, Color col) const override;
        int getTextHeight() const override;
        void getTextSize(const UTF8String &text, int &w, int &h) const override;
        size_t getStringIndexAt(const UTF8String &text, int x) const override;

    private:
        // Cached glyph information (stored in the atlas).
        struct CachedGlyph {
            Rectangle atlas_rect;  // Position and size within the atlas texture
            int atlas_index = 0;   // Which atlas this glyph is stored in
            int xofs = 0;          // Offset from pen position to top-left of glyph
            int yofs = 0;
            int xadvance = 0;      // How far to advance pen after drawing
            bool has_pixels = false;  // False for space and other invisible glyphs
        };

        // Ensure a glyph is in the cache, creating it if necessary.
        const CachedGlyph& ensureGlyph(char32_t codepoint) const;

        // Add a glyph to the atlas. Returns false if atlas is full.
        bool addGlyphToAtlas(char32_t codepoint, CachedGlyph &glyph) const;

        // Create a new atlas (when current one is full).
        void createNewAtlas() const;

        // Get kerning between two codepoints (with caching).
        int getKern(char32_t left, char32_t right) const;

    private:
        boost::shared_ptr<GfxDriver> gfx_driver;
        std::unique_ptr<GlyphCreator> glyph_creator;

        int atlas_width;
        int atlas_height;

        // Mutable because glyphs are loaded lazily during const drawText/getTextSize.
        mutable std::vector<boost::shared_ptr<Graphic>> atlases;
        mutable std::unordered_map<char32_t, CachedGlyph> glyph_cache;

        // Shelf packing state for the current atlas.
        mutable int current_shelf_y = 0;      // Y position of current shelf
        mutable int current_shelf_height = 0; // Height of current shelf
        mutable int current_x = 0;            // X position within current shelf

        // Kerning cache: key is (left << 32) | right, value is kern amount
        mutable std::unordered_map<uint64_t, int> kern_cache;
    };

}

#endif
