/*
 * FILE:
 *   cg_listener.cpp
 *
 * AUTHOR:
 *   Stephen Thompson
 *
 * COPYRIGHT:
 *   Copyright (C) Stephen Thompson, 2008 - 2025.
 *
 *   This file is part of the "Coercri" software library. Usage of "Coercri"
 *   is permitted under the terms of the Boost Software License, Version 1.0, 
 *   the text of which is displayed below.
 *
 *   Boost Software License - Version 1.0 - August 17th, 2003
 *
 *   Permission is hereby granted, free of charge, to any person or organization
 *   obtaining a copy of the software and accompanying documentation covered by
 *   this license (the "Software") to use, reproduce, display, distribute,
 *   execute, and transmit the Software, and to prepare derivative works of the
 *   Software, and to permit third-parties to whom the Software is furnished to
 *   do so, all subject to the following:
 *
 *   The copyright notices in the Software and this entire statement, including
 *   the above license grant, this restriction and the following disclaimer,
 *   must be included in all copies of the Software, in whole or in part, and
 *   all derivative works of the Software, unless such copies or derivative
 *   works are solely in the form of machine-executable object code generated by
 *   a source language processor.
 *
 *   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *   FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 *   SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 *   FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 *   ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 *   DEALINGS IN THE SOFTWARE.
 *
 */

#include "cg_graphics.hpp"
#include "cg_input.hpp"
#include "cg_listener.hpp"
#include "text_input_receiver.hpp"
#include "../core/utf8string.hpp"
#include "../gfx/window.hpp"
#include "../timer/timer.hpp"

#include "guichan.hpp"

namespace Coercri {

    namespace {
        void SendKeyToGuichan(CGInput &input, gcn::Key k, KeyModifier mods)
        {
            // create two Guichan events: one pressed, and one released.
            gcn::KeyInput key_input(k, gcn::KeyInput::PRESSED);
            key_input.setAltPressed((mods & KM_ALT) != 0);
            key_input.setControlPressed((mods & KM_CONTROL) != 0);
            key_input.setShiftPressed((mods & KM_SHIFT) != 0);
            // note: we don't support guichan's "meta" modifer and "numeric pad" flag.
            input.addKeyInput(key_input);
            key_input.setType(gcn::KeyInput::RELEASED);
            input.addKeyInput(key_input);
        }
    }

    class CGListenerImpl {
    public:
        CGListenerImpl(boost::shared_ptr<Window> win, boost::shared_ptr<gcn::Gui> g, boost::shared_ptr<Timer> tmr)
            : window(win), gui(g), timer(tmr), input(tmr), gui_enabled(false),
              last_mouse_x(0), last_mouse_y(0)
        { }
        
        boost::shared_ptr<Window> window;
        boost::shared_ptr<gcn::Gui> gui;
        boost::shared_ptr<Timer> timer;
        
        CGInput input;
        CGGraphics graphics;
        
        bool gui_enabled;
        int last_mouse_x, last_mouse_y;
    };
    
    CGListener::CGListener(boost::shared_ptr<Window> window, boost::shared_ptr<gcn::Gui> gui, boost::shared_ptr<Timer> timer)
        : pimpl(new CGListenerImpl(window, gui, timer))
    {
        pimpl->gui->setInput(&pimpl->input);
        pimpl->gui->setGraphics(&pimpl->graphics);
    }

    void CGListener::enableGui()
    {
        if (pimpl->gui_enabled) return;
        pimpl->gui_enabled = true;

        // Window may have been resized while the GUI was disabled, so do a resize now.
        int w, h;
        pimpl->window->getSize(w, h);
        onResize(w, h);
    }

    void CGListener::disableGui()
    {
        pimpl->gui_enabled = false;
    }

    bool CGListener::isGuiEnabled() const
    {
        return pimpl->gui_enabled;
    }

    bool CGListener::processInput()
    {
        if (!pimpl->gui_enabled) return false;
        
        if (pimpl->input.inputWaiting()) {
            pimpl->gui->logic();
            pimpl->window->invalidateAll();
            return true;
        } else {
            return false;
        }
    }
    
    void CGListener::draw(GfxContext &gc)
    {
        if (!pimpl->gui_enabled) return;

        pimpl->gui->logic();
        
        pimpl->graphics.setTarget(&gc);
        pimpl->gui->draw();
        pimpl->graphics.setTarget(0);
    }

    void CGListener::onResize(int new_width, int new_height)
    {
        if (!pimpl->gui_enabled) return;
        
        if (pimpl->gui->getTop()) {
            pimpl->gui->getTop()->setSize(new_width, new_height);
            pimpl->window->invalidateAll();  // make sure it gets redrawn.
        }
    }

    void CGListener::onKey(KeyEventType type, const Scancode &scancode, KeyModifier mods)
    {
        // only process PRESSED and AUTO_REPEAT events here.
        if (type == KEY_RELEASED) return;

        // only process 'special' keys. (the normal "text" keys will be
        // processed by onTextInput.)

        // note: this does mean guichan will not get keypresses such as ctrl+c currently 
        // (because these are neither a special key nor do they generate a text event.)
        // but guichan doesn't do anything with such keypresses (afaik) so hopefully 
        // this won't matter.

        const std::string & name = scancode.getSymbolicName();
        if (name.length() == 0) return;  // shouldn't happen

        gcn::Key k = 0;
        switch (name[0]) {
        case 'b':
            if (name == "backspace") k = gcn::Key::BACKSPACE;
            break;

        case 'd':
            if (name == "delete") k = gcn::Key::DELETE;
            else if (name == "down") k = gcn::Key::DOWN;
            break;

        case 'e':
            if (name == "end") k = gcn::Key::END;
            else if (name == "escape") k = gcn::Key::ESCAPE;
            break;

        case 'f':
            if (name.length() == 2) {
                switch (name[1]) {
                case '1': k = gcn::Key::F1; break;
                case '2': k = gcn::Key::F2; break;
                case '3': k = gcn::Key::F3; break;
                case '4': k = gcn::Key::F4; break;
                case '5': k = gcn::Key::F5; break;
                case '6': k = gcn::Key::F6; break;
                case '7': k = gcn::Key::F7; break;
                case '8': k = gcn::Key::F8; break;
                case '9': k = gcn::Key::F9; break;
                }
            } else if (name.length() == 3 && name[1] == '1') {
                switch (name[2]) {
                case '0': k = gcn::Key::F10; break;
                case '1': k = gcn::Key::F11; break;
                case '2': k = gcn::Key::F12; break;
                case '3': k = gcn::Key::F13; break;
                case '4': k = gcn::Key::F14; break;
                case '5': k = gcn::Key::F15; break;
                }
            }
            break;

        case 'h':
            if (name == "home") k = gcn::Key::HOME;
            break;

        case 'i':
            if (name == "insert") k = gcn::Key::INSERT;
            break;

        case 'k':
            if (name == "kp_enter") k = gcn::Key::ENTER;
            break;

        case 'l':
            if (name == "left") k = gcn::Key::LEFT;
            else if (name == "left_windows") k = gcn::Key::LEFT_SUPER;
            break;

        case 'p':
            if (name == "page_down") k = gcn::Key::PAGE_DOWN;
            else if (name == "page_up") k = gcn::Key::PAGE_UP;
            else if (name == "pause") k = gcn::Key::PAUSE;
            else if (name == "print_screen") k = gcn::Key::PRINT_SCREEN;
            break;

        case 'r':
            if (name == "return") k = gcn::Key::ENTER;
            else if (name == "right") k = gcn::Key::RIGHT;
            else if (name == "right_windows") k = gcn::Key::RIGHT_SUPER;
            break;

        case 't':
            if (name == "tab") k = gcn::Key::TAB;
            break;

        case 'u':
            if (name == "up") k = gcn::Key::UP;
            break;
        }

        if (k != 0) {
            SendKeyToGuichan(pimpl->input, k, mods);
        }
    }

    void CGListener::onTextInput(const UTF8String &txt_in)
    {
        if (!pimpl->gui_enabled) return;

        // Get the currently focused widget
        gcn::Widget *focused = pimpl->gui->getTop()->_getFocusHandler()->getFocused();

        if (focused) {
            // Try to cast to TextInputReceiver
            TextInputReceiver *receiver = dynamic_cast<TextInputReceiver*>(focused);

            if (receiver) {
                // Direct text insertion for widgets that support UTF-8
                receiver->receiveTextInput(txt_in);
                pimpl->window->invalidateAll();
            }
            // else: widget doesn't support UTF-8 text input, drop the input
        }
    }
    
    void CGListener::onMouseDown(int x, int y, MouseButton button)
    {
        if (!pimpl->gui_enabled) return;
        
        unsigned int b, t;
        switch (button) {
        case MB_LEFT:
            b = gcn::MouseInput::LEFT;
            t = gcn::MouseInput::PRESSED;
            break;
        case MB_RIGHT:
            b = gcn::MouseInput::RIGHT;
            t = gcn::MouseInput::PRESSED;
            break;
        case MB_MIDDLE:
            b = gcn::MouseInput::MIDDLE;
            t = gcn::MouseInput::PRESSED;
            break;
        case MB_WHEEL_UP:
            b = gcn::MouseInput::EMPTY;
            t = gcn::MouseInput::WHEEL_MOVED_UP;
            break;
        case MB_WHEEL_DOWN:
            b = gcn::MouseInput::EMPTY;
            t = gcn::MouseInput::WHEEL_MOVED_DOWN;
            break;
        default:
            return;
        }
        const int timestamp = pimpl->timer ? pimpl->timer->getMsec() : 0;

        pimpl->input.addMouseInput(gcn::MouseInput(b, t, x, y, timestamp));
        pimpl->last_mouse_x = x;
        pimpl->last_mouse_y = y;
    }

    void CGListener::onMouseUp(int x, int y, MouseButton button)
    {
        if (!pimpl->gui_enabled) return;
        
        unsigned int b;
        switch (button) {
        case MB_LEFT: b = gcn::MouseInput::LEFT; break;
        case MB_RIGHT: b = gcn::MouseInput::RIGHT; break;
        case MB_MIDDLE: b = gcn::MouseInput::MIDDLE; break;
        default: return;
        }
        const int timestamp = pimpl->timer ? pimpl->timer->getMsec() : 0;
        pimpl->input.addMouseInput(gcn::MouseInput(b, gcn::MouseInput::RELEASED, x, y, timestamp));
        pimpl->last_mouse_x = x;
        pimpl->last_mouse_y = y;
    }

    void CGListener::onMouseMove(int x, int y)
    {
        if (!pimpl->gui_enabled) return;
        
        const int timestamp = pimpl->timer ? pimpl->timer->getMsec() : 0;
        pimpl->input.addMouseInput(gcn::MouseInput(gcn::MouseInput::EMPTY, gcn::MouseInput::MOVED, x, y, timestamp));
        pimpl->last_mouse_x = x;
        pimpl->last_mouse_y = y;
    }

    void CGListener::repeatLastMouseInput()
    {
        onMouseMove(pimpl->last_mouse_x, pimpl->last_mouse_y);
    }
}
