/*
 * FILE:
 *   generic_timer.cpp
 *
 * AUTHOR:
 *   Stephen Thompson <stephen@solarflare.org.uk>
 *
 * CREATED:
 *   21-Oct-2011
 *   
 * COPYRIGHT:
 *   Copyright (C) Stephen Thompson, 2008 - 2025.
 *
 *   This file is part of the "Coercri" software library. Usage of "Coercri"
 *   is permitted under the terms of the Boost Software License, Version 1.0, 
 *   the text of which is displayed below.
 *
 *   Boost Software License - Version 1.0 - August 17th, 2003
 *
 *   Permission is hereby granted, free of charge, to any person or organization
 *   obtaining a copy of the software and accompanying documentation covered by
 *   this license (the "Software") to use, reproduce, display, distribute,
 *   execute, and transmit the Software, and to prepare derivative works of the
 *   Software, and to permit third-parties to whom the Software is furnished to
 *   do so, all subject to the following:
 *
 *   The copyright notices in the Software and this entire statement, including
 *   the above license grant, this restriction and the following disclaimer,
 *   must be included in all copies of the Software, in whole or in part, and
 *   all derivative works of the Software, unless such copies or derivative
 *   works are solely in the form of machine-executable object code generated by
 *   a source language processor.
 *
 *   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *   FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 *   SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 *   FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 *   ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 *   DEALINGS IN THE SOFTWARE.
 *
 */

#include "generic_timer.hpp"

#ifdef WIN32
#include <windows.h>
#ifdef min
#undef min
#endif
#ifdef max
#undef max
#endif
#endif

#ifdef __linux__
#include <time.h>
#include <unistd.h>
#endif

namespace Coercri {

#ifdef WIN32
    namespace {
        int g_timer_use_count = 0;
        bool g_use_perf_counter;
        LARGE_INTEGER g_perf_freq;
    }
#endif
    
    GenericTimer::GenericTimer()
    {
#ifdef WIN32
        if (g_timer_use_count == 0) {
            // use QueryPerformanceCounter if available, timeGetTime
            // otherwise.
            g_use_perf_counter = (QueryPerformanceFrequency(&g_perf_freq) != 0);
            if (!g_use_perf_counter) {
                timeBeginPeriod(1);
            }
            ++g_timer_use_count;
        }
#endif
    }

    GenericTimer::~GenericTimer()
    {
#ifdef WIN32
        --g_timer_use_count;
        if (g_timer_use_count == 0 && !g_use_perf_counter) {
            timeEndPeriod(1);
        }
#endif        
    }

    uint64_t GenericTimer::getUsec()
    {
#ifdef WIN32
        if (g_use_perf_counter) {
            LARGE_INTEGER perf_count;
            QueryPerformanceCounter(&perf_count);

            // Convert to microseconds.
            // Split the calculation into two parts to avoid overflow issues.
            uint64_t ticks = perf_count.QuadPart;
            uint64_t ticks_per_sec = g_perf_freq.QuadPart;
            uint64_t microseconds = (ticks / ticks_per_sec) * 1000000u;
            uint64_t remainder = ticks % ticks_per_sec;
            microseconds += (remainder * 1000000u) / ticks_per_sec;

            return microseconds;
            
        } else {
            // timeGetTime returns milliseconds, multiply by 1000 to convert to microseconds
            return uint64_t(timeGetTime()) * 1000;
        }

#elif defined(__linux__)
        struct timespec now;
        clock_gettime(CLOCK_MONOTONIC, &now);
        uint64_t seconds = now.tv_sec;
        uint64_t nanoseconds = now.tv_nsec;
        return (seconds * 1000000u) + (nanoseconds / 1000u);

#else
#error "Timer not implemented for this operating system!"
#endif
    }

    unsigned int GenericTimer::getMsec()
    {
        return getUsec() / 1000;
    }

    void GenericTimer::sleepUsec(int64_t usec)
    {
        if (usec > 0) {
#ifdef WIN32
            // Sleep takes milliseconds. (I do not know of any
            // microsecond-sleep API in windows.)

            // We round UP the sleep time to the next higher whole
            // number of milliseconds. This is because the spec says
            // we have to sleep for AT LEAST the given time, so
            // rounding up is appropriate.

            Sleep((usec + 999) / 1000);

#elif defined(__linux__)

            // On Linux we use nanosleep
            struct timespec ts;
            ts.tv_sec = usec / 1000000;
            ts.tv_nsec = (usec % 1000000) * 1000;
            nanosleep(&ts, NULL);
#endif
        }
    }

    void GenericTimer::sleepMsec(int msec)
    {
        sleepUsec(msec * 1000);
    }
}
